version: "2"
services: 
  frontend:
    image: 'react-frontend'
    build: frontend/
    container_name: react-frontend
    ports:
      - "3000:3000"

  backend:
    image: 'java-backend'
    build: backend/
    container_name: java-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/urlshortener
      - SPRING_DATASOURCE_USERNAME=urlshortener
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=urlshortener
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
   


    
  
