spring:
  security:
    user:
      name: user
      password: pwd

    oauth2:
      client:
        registration:
          google:
            client-id: 14709625245-cmprt3nttq7461f7o8s12rvpgpnsd7ip.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: 7cd1542d0816be19c267
            client-secret: c38b638917285df6e733cf2a2e4bd627ba5cd119
  datasource:
    url: 'jdbc:postgresql://localhost:5432/urlshortener'
    username: pdabre12
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd
  main:
    allow-circular-references: true
server:
  port: '8080'
  use-forward-header: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
jwt:
  secret: "14709625245cmprt3nttq7461f7o8s12rvpgpnsd7iappsgoogleusercontentcom"
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
        boot:
          autoconfigure:
            security: INFO
org:
  springframework:
    boot:
      autoconfigure:
        security: INFO






